spring:
  application:
    name: kotlin-spring-api
  profiles:
    active: [ dev ]
  jackson:
    default-property-inclusion: non_null

application:
  title: kotlin-spring-api
  version: 1.0.0
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

