create table book (
  id integer generated by default as identity,
  name varchar(255) not null,
  price decimal(10,2) not null,
  status integer not null,
  customer_id int not null,
  foreign key (customer_id) references customer(id),
  primary key (id)
)